### ISSUE TITLE
Error al guardar ubicación de proyecto de inversión

### ISSUE THREAD

**Issue by sergiochtf** [consul/consul#1553]
Al crear un proyecto de inversión y rellenar el campo "Localización" el valor no se guarda en la base de datos y al cargar la información del proyecto de inversión no se muestra. Sin embargo, he realizado una prueba y rellenar el valor de la localización del proyecto por base de datos y éste si se muestra correctamente.

**Comment by decabeza** [comment]
Hi @sergiochtf!

I just test locally and it seems working... Could you try again or provide more information? Thanks!

![location_console](https://cloud.githubusercontent.com/assets/631897/26226735/46dc69f2-3c2e-11e7-851d-cdbe9b495c3a.png)

![location_front](https://cloud.githubusercontent.com/assets/631897/26226736/46e15232-3c2e-11e7-84fe-c0006eaffa74.png)

**Comment by sergiochtf** [comment]
Hi! @decabeza.

I try again with the same result. I attach some screenshots.
![1](https://cloud.githubusercontent.com/assets/9718722/26237728/3f25529c-3c6e-11e7-903b-13660d32550c.png)
![2](https://cloud.githubusercontent.com/assets/9718722/26237729/3f45309e-3c6e-11e7-8b16-70932cd05a4e.png)
![3](https://cloud.githubusercontent.com/assets/9718722/26237845/af5d1aa4-3c6e-11e7-99b9-95e2f3033b8d.png)

**Comment by xuanxu** [comment]
hey @sergiochtf, good eye, location was missing in the list of permitted params. 
[This PR](https://github.com/consul/consul/pull/1554) fixes it. Once is merged you can just pull from master and issue should be solved.

**Comment by sergiochtf** [comment]
Hi @xuanxu, I downloaded the 3 files of the commit, but the behavior is the same, still does not save the location, need to do something more than replace 3 files and run the application?

**Comment by xuanxu** [comment]
@sergiochtf yep, no extra steps are needed, doing a git pull from master and restarting the server should do the trick
