### ISSUE TITLE
Add heading name to the "no supports on more than X heading" alert

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2496]
Background
==
Currently, we limit the user supports to just one heading per Budget group. When the user tries to support in a second heading he gets the alert message `You can only support investment projects in one heading`

What we need
==
We need to include the heading name where the user has already supported. It will help clarify the error and even let the user undo the supports on that heading

Screenshot
==
**One heading to support/vote**
![heading link](https://user-images.githubusercontent.com/631897/37102501-40f5c854-2228-11e8-9b86-87a02708d3f1.png)

**Example with various headings to support/vote**
<img width="892" alt="screen shot 2018-03-27 at 19 13 56" src="https://user-images.githubusercontent.com/631897/37983244-325b3a2e-31f3-11e8-88df-0a74ac4f41e1.png">

**Comment by aitbw** [comment]
I'm assuming this is already solved through #2528, right?

**Comment by decabeza** [comment]
Hi @aitbw, still not complete because we have the new **"Maximum number of headings in which a user can support"** attribute.

Now the message show the max heading you can vote but not the links to the other headings.

**Actual message**
![screen shot 2018-05-29 at 15 34 45](https://user-images.githubusercontent.com/631897/40662230-08bea0f4-6356-11e8-9052-d272fc33ee28.png)

**We want this** 😌 
<img width="892" alt="screen shot 2018-03-27 at 19 13 56" src="https://user-images.githubusercontent.com/631897/37983244-325b3a2e-31f3-11e8-88df-0a74ac4f41e1.png">

**Comment by mlovic** [comment]
I'll get started on this one
